tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up


ports:
  - port: 5601
    onOpen: open-preview
  - port: 9200
    onOpen: ignore
  - port: 9600
    onOpen: ignore