tasks:
  - name: Tutorial server
    init: |
      python3 -m http.server 8080
  - init: |
      docker-compose pull
  - command: |
      docker-compose up


ports:
  - port: 8080
    onOpen: open-preview
  - port: 5601
    onOpen: open-preview
  - port: 9200
    onOpen: ignore
  - port: 9600
    onOpen: ignore